### ISSUE TITLE
maxPower field is not updating the value

### ISSUE THREAD

**Issue by Rollerf** [orbis-developers/home_assistant_viaris#3]
# My devices:
- Home Assistant:
![image](https://github.com/orbis-developers/home_assistant_viaris/assets/35430972/79a60cc3-6855-40eb-ad4d-fe6c4518efbc)
- HACS:
![image](https://github.com/orbis-developers/home_assistant_viaris/assets/35430972/28bdcd79-768c-476a-9a0f-0bd04898cf42)
- Viaris device:
![image](https://github.com/orbis-developers/home_assistant_viaris/assets/35430972/540f2bfb-1fbf-4efb-b1fe-80232586399d)

# Description of the problem:
- I integrated this in home assistant and maxPower sensor gives me 7.36kw but I had configured 4.4kw on the charger.
![image](https://github.com/orbis-developers/home_assistant_viaris/assets/35430972/f02da065-e9a8-440d-ae41-5c5e0e62e2ef)
In the message topic "/streamrt/modulator" I can see the correct value:
![image](https://github.com/orbis-developers/home_assistant_viaris/assets/35430972/23cdce03-1d2a-4ff5-abc1-2341b0e37e85)

# Soution:
- I updated the MQTT subscription from "/boot/sys" to "/streamrt/modulator" and it started to work fine.

Great job with the integration, easy to install and zero configuration. I love it!

**Comment by HGC72** [comment]
Hi!
Thank you for installing our integration and for wanting to collaborate with us. 
The value we refer to in the "/boot/sys" topic is different from that in "/streamrt/modulator." In the former, we indicate the maximum power of the device, which does not always coincide with the working value. As you may already know, the working value depends on power ranges, contracted power, etc., and it is the one displayed in "/streamrt/modulator." Due to this difference and other incompatibilities, we regret to inform you that we cannot approve the merge. However, we will consider incorporating a new entity in future versions that displays the value of "/streamrt/modulator."
Regards,

**Comment by Rollerf** [comment]
Hello @HGC72, thanks for the explanation.
I'm sorry for the incorrect PR, you are completely right. I corrected it and made a new PR. I hope this time it's correct.
Thanks for provide this amazing integration, best regards!

**Comment by HGC72** [comment]
Hi, Rollerf
I close this issue because there was no problem with this maximum power.
Regards.
